'use client'

import { useState } from 'react'
import { useGameStore } from '@/store/gameStore'
import { motion, AnimatePresence } from 'framer-motion'

interface ProvablyFairModalProps {
  isOpen: boolean
  onClose: () => void
}

export default function ProvablyFairModal({ isOpen, onClose }: ProvablyFairModalProps) {
  const seeds = useGameStore((state) => state.seeds)
  const recentResults = useGameStore((state) => state.recentResults)
  const changeClientSeed = useGameStore((state) => state.changeClientSeed)

  const [newClientSeed, setNewClientSeed] = useState('')
  const [selectedResult, setSelectedResult] = useState<string | null>(null)

  const handleChangeClientSeed = () => {
    if (newClientSeed.trim()) {
      changeClientSeed(newClientSeed.trim())
      setNewClientSeed('')
      alert('Client seed changed successfully!')
    }
  }

  const selectedBet = selectedResult
    ? recentResults.find(r => r.id === selectedResult)
    : null

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-70">
          <motion.div
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            className="bg-background-secondary border border-gray-700 rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto"
          >
            {/* Header */}
            <div className="border-b border-gray-700 p-4 flex items-center justify-between sticky top-0 bg-background-secondary">
              <h2 className="text-xl font-bold text-accent-blue">Provably Fair</h2>
              <button
                onClick={onClose}
                className="text-gray-400 hover:text-white text-2xl"
                aria-label="Close modal"
              >
                ×
              </button>
            </div>

            {/* Content */}
            <div className="p-6 space-y-6">
              {/* Current Seeds */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-gray-300">Current Seeds</h3>

                <div>
                  <label className="text-sm text-gray-400">Server Seed (Hashed)</label>
                  <div className="mt-1 p-2 bg-gray-800 rounded font-mono text-xs break-all">
                    {seeds.serverSeedHash}
                  </div>
                </div>

                <div>
                  <label className="text-sm text-gray-400">Client Seed</label>
                  <div className="mt-1 p-2 bg-gray-800 rounded font-mono text-xs break-all">
                    {seeds.clientSeed}
                  </div>
                </div>

                <div>
                  <label className="text-sm text-gray-400">Nonce</label>
                  <div className="mt-1 p-2 bg-gray-800 rounded font-mono text-xs">
                    {seeds.nonce}
                  </div>
                </div>
              </div>

              {/* Change Client Seed */}
              <div className="border-t border-gray-700 pt-4">
                <h3 className="text-lg font-semibold text-gray-300 mb-3">Change Client Seed</h3>
                <p className="text-sm text-gray-400 mb-3">
                  Changing your client seed will also generate a new server seed and reset the nonce.
                </p>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newClientSeed}
                    onChange={(e) => setNewClientSeed(e.target.value)}
                    placeholder="Enter new client seed"
                    className="flex-1 bg-gray-800 border border-gray-700 rounded px-3 py-2 text-sm"
                  />
                  <button
                    onClick={handleChangeClientSeed}
                    disabled={!newClientSeed.trim()}
                    className="px-4 py-2 bg-accent-blue hover:bg-blue-600 disabled:bg-gray-700 disabled:text-gray-500 rounded text-sm font-medium transition-colors"
                  >
                    Change
                  </button>
                </div>
              </div>

              {/* How It Works */}
              <div className="border-t border-gray-700 pt-4">
                <h3 className="text-lg font-semibold text-gray-300 mb-3">How It Works</h3>
                <div className="space-y-2 text-sm text-gray-400">
                  <p>
                    1. <strong className="text-gray-300">Server Seed:</strong> A random seed generated by the server. Only the hash is shown to you before each bet.
                  </p>
                  <p>
                    2. <strong className="text-gray-300">Client Seed:</strong> A seed you can change at any time to influence the outcome.
                  </p>
                  <p>
                    3. <strong className="text-gray-300">Nonce:</strong> An incrementing number for each bet to ensure uniqueness.
                  </p>
                  <p>
                    4. The combination of all three values determines the outcome in a deterministic way that cannot be manipulated.
                  </p>
                </div>
              </div>

              {/* Recent Results Verification */}
              {recentResults.length > 0 && (
                <div className="border-t border-gray-700 pt-4">
                  <h3 className="text-lg font-semibold text-gray-300 mb-3">Verify Recent Results</h3>
                  <div className="space-y-2 max-h-60 overflow-y-auto">
                    {recentResults.slice(0, 10).map((result) => (
                      <div
                        key={result.id}
                        onClick={() => setSelectedResult(result.id)}
                        className={`p-3 rounded cursor-pointer transition-colors ${
                          selectedResult === result.id
                            ? 'bg-accent-blue bg-opacity-20 border border-accent-blue'
                            : 'bg-gray-800 hover:bg-gray-700'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2 text-sm">
                            <span className="text-gray-400">
                              ${result.betAmount.toFixed(2)}
                            </span>
                            <span className="text-gray-500">×</span>
                            <span className="font-mono font-bold text-accent-gold">
                              {result.multiplier}x
                            </span>
                          </div>
                          <div className={`text-sm font-mono ${result.profit > 0 ? 'text-green-400' : 'text-red-400'}`}>
                            {result.profit > 0 ? '+' : ''}${result.profit.toFixed(2)}
                          </div>
                        </div>
                        {selectedResult === result.id && (
                          <div className="mt-2 pt-2 border-t border-gray-700 text-xs space-y-1">
                            <div className="text-gray-400">
                              Server Seed Hash: <span className="font-mono">{result.seeds.serverSeed}</span>
                            </div>
                            <div className="text-gray-400">
                              Client Seed: <span className="font-mono">{result.seeds.clientSeed}</span>
                            </div>
                            <div className="text-gray-400">
                              Nonce: <span className="font-mono">{result.seeds.nonce}</span>
                            </div>
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Info */}
              <div className="border-t border-gray-700 pt-4">
                <div className="bg-blue-900 bg-opacity-30 border border-blue-700 rounded p-3 text-sm text-gray-300">
                  <strong className="text-accent-blue">Note:</strong> This is a demonstration of a provably fair system.
                  In a production environment, you would be able to verify results using cryptographic functions.
                </div>
              </div>
            </div>

            {/* Footer */}
            <div className="border-t border-gray-700 p-4 flex justify-end">
              <button
                onClick={onClose}
                className="px-6 py-2 bg-gray-700 hover:bg-gray-600 rounded font-medium transition-colors"
              >
                Close
              </button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}
